# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Storybook

on: pull_request

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache 
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

  lint:
    name: Lint step
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Lint the app
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install
          yarn run lint
      - uses: actions/upload-artifact@master
        with:
          name: lintingLog
          path: eslintLog.html
  build:
    name: Build app
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build the app
        run: |
          yarn install
          yarn build
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build
